---

- name: Include facts.yml
  include: facts.yml

- name: Include selinux.yml
  include: selinux.yml

- name: Include monitors.yml
  include: monitors.yml

- name: Include managers.yml
  include: managers.yml

- name: Include osds.yml
  include: osds.yml

- name: Include mdss.yml
  include: mdss.yml

- name: Include tweaks.yml
  include: tweaks.yml

- name: Include cephfs.yml
  include: cephfs.yml

